create table if not exists public.atm_data (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null,
  futures_price double precision not null,
  atm_strike integer not null,
  ce_price double precision,
  pe_price double precision,
  futures_symbol text
);

create index if not exists atm_data_timestamp_idx
  on public.atm_data (timestamp desc);

-- Recommended for this private backend tracker:
-- Use SUPABASE_KEY as a Supabase secret key or service_role key so inserts bypass
-- RLS without exposing write access to public clients.
--
-- If you intentionally want to use a publishable/anon key, enable RLS and add
-- the policies below. This allows any holder of that key to insert and read
-- atm_data, so use it only for a private project/key.
alter table public.atm_data enable row level security;

drop policy if exists "atm_data_insert_with_anon_or_authenticated_key" on public.atm_data;
create policy "atm_data_insert_with_anon_or_authenticated_key"
  on public.atm_data
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "atm_data_read_with_anon_or_authenticated_key" on public.atm_data;
create policy "atm_data_read_with_anon_or_authenticated_key"
  on public.atm_data
  for select
  to anon, authenticated
  using (true);
